language: php

php:
  - 5.5
  - 5.6
  - hhvm

env:
  - COMPOSER_ROOT_VERSION=dev-master

install:
  - composer self-update
  - composer update

script:
  - phpunit tests
  - ./tests/lint.sh

git:
  depth: 5
